// Import generated proto message types
// These are generated by ts_proto_library from rules_proto_grpc
// Note: Import paths may need adjustment based on actual generated code structure
// Import generated proto message types
// These are generated by ts_proto_library from rules_proto_grpc
// Note: Import paths may need adjustment based on actual generated code structure
import { Player, ListPlayersRequest, ListPlayersResponse } from './ladder_pb'

// Import generated gRPC-Web service client
// This is generated by js_grpc_web_library from rules_proto_grpc
// Note: js_grpc_web_library may generate code for official grpc-web library
// If so, the API and import paths will need adjustment
import { LadderServiceClient } from './ladder_grpc_web_pb'

// Re-export types for convenience
export type { Player, ListPlayersRequest, ListPlayersResponse }

// Create a service client instance
// The generated client provides type-safe methods for each RPC
const client = new LadderServiceClient('/players') // Keep usage of /players if Nginx proxy still maps it? Or should it be /ladder? Or is it pure gRPC path? gRPC path is /package.Service/Method.
// Protocol buffers usually use [package].[Service]/[Method] in HTTP/2.
// gRPC-Web might default to that.
// The constructor argument in generated client usually suggests the hostname or prefix.
// If Nginx handles it, usually it's empty string or full URL.
// The previous code had '/players'. This might be a prefix?
// Let's keep it '/players' for now if that's the Nginx location, but wait, `services` in proto is `LadderService`.
// If the path is /ladder.LadderService/ListPlayers, and Nginx forwards /players to that...
// Let's check Nginx config later. But for now I'll change the import and client class.

// Service wrapper that uses the generated client
// This provides a cleaner async/await interface over the generated client
export const ladderService = {
  listPlayers: async (): Promise<ListPlayersResponse> => {
    return new Promise((resolve, reject) => {
      // Create request message (empty for ListPlayersRequest)
      const request = new ListPlayersRequest()

      // Use the generated client method
      // The generated code provides type-safe method definitions
      client.listPlayers(request, {}, (err: any, response: any) => {
        if (err) {
          reject(new Error(`gRPC error: ${err.message || 'Unknown error'}`))
        } else if (response) {
          resolve(response)
        } else {
          reject(new Error('No response received'))
        }
      })
    })
  },
}
