// Import generated proto message types
// These are generated by ts_proto_library from rules_proto_grpc
// Note: Import paths may need adjustment based on actual generated code structure
import { Player, ListPlayersRequest, ListPlayersResponse } from './players_pb'

// Import generated gRPC-Web service client
// This is generated by js_grpc_web_library from rules_proto_grpc
// Note: js_grpc_web_library may generate code for official grpc-web library
// If so, the API and import paths will need adjustment
import { PlayersServiceClient } from './players_grpc_web_pb'

// Re-export types for convenience
export type { Player, ListPlayersRequest, ListPlayersResponse }

// Create a service client instance
// The generated client provides type-safe methods for each RPC
const client = new PlayersServiceClient('http://localhost:8080')

// Service wrapper that uses the generated client
// This provides a cleaner async/await interface over the generated client
export const playersService = {
  listPlayers: async (): Promise<ListPlayersResponse> => {
    return new Promise((resolve, reject) => {
      // Create request message (empty for ListPlayersRequest)
      const request = new ListPlayersRequest()

      // Use the generated client method
      // The generated code provides type-safe method definitions
      client.listPlayers(request, {}, (err: any, response: any) => {
        if (err) {
          reject(new Error(`gRPC error: ${err.message || 'Unknown error'}`))
        } else if (response) {
          resolve(response)
        } else {
          reject(new Error('No response received'))
        }
      })
    })
  },
}
